service: holidaycheck

custom:
  dotenv:
    basePath: ./config/
  stage: ${env:STAGE}
  prod:
    GW_URL: { "Fn::Join" : ["", [ "https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.us-east-1.amazonaws.com/${env:STAGE}" ] ] }
  dev:
    GW_URL: "http://localhost:3000"

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:STAGE}
  region: us-east-1
  environment:
    GW_URL: ${self:custom.${self:custom.stage}.GW_URL}

functions:
  # hello:
  #   handler: handler.hello
  app:
    handler: handler.server
    events:
      - http: 
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
